//! macOS `launchd` service install (A.8.2) — symmetric companion to
//! [`super::systemd`] for hosts running macOS.
//!
//! Renders a `/Library/LaunchDaemons/com.veriguard.<service_name>.plist`
//! XML PropertyList that `launchctl bootstrap system` loads on boot.
//! Pure render is fully unit-tested; the `launchctl` orchestration runs
//! the real commands only when not in dry-run mode.
//!
//! ## Hardening
//!
//! The generated plist applies a defensive baseline that mirrors the
//! systemd unit's intent within launchd's vocabulary:
//!
//! - `RunAtLoad=true` + `KeepAlive=true` — boot-start + restart on crash
//! - `UserName` / `GroupName` from [`SystemdConfig::service_user`] so the
//!   daemon never runs as root unless the operator explicitly says so
//! - `ProcessType=Background` — opt out of front-of-app QoS scheduling
//! - `StandardOutPath` / `StandardErrorPath` → `/var/log/<name>.{out,err}.log`
//!   so admins have a `tail -f` story without `journalctl`
//! - `WorkingDirectory` = configured `state_dir` so relative paths inside
//!   the agent resolve correctly under launchd
//!
//! macOS-specific sandbox keys (`SoftResourceLimits` / `LowPriorityIO`)
//! are intentionally left to ops to tighten further.
//!
//! ## Cross-platform type reuse
//!
//! Both [`super::install_service`] and [`super::uninstall_service`] take
//! the existing [`SystemdConfig`] / [`SystemdUninstallConfig`] structs —
//! the "Systemd" prefix is historical; the field set (binary_path,
//! state_dir, service_name, service_user, enable_on_install, dry_run) is
//! cross-platform in spirit. This module reuses those types so the
//! dispatcher in [`super`] does not need a tagged-union config.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

use super::error::InstallError;
use super::systemd::{validate_absolute, validate_identifier, SystemdConfig, SystemdInstallReport};
use super::uninstall::{SystemdUninstallConfig, SystemdUninstallReport};

/// Standard system-wide launchd plist directory.
pub const DEFAULT_LAUNCHD_PLIST_DIR: &str = "/Library/LaunchDaemons";

/// Reverse-DNS prefix for the launchd Label. The full Label is
/// `com.veriguard.<service_name>` — operators recognize the namespace at
/// a glance in `launchctl list`.
pub const LABEL_PREFIX: &str = "com.veriguard";

/// Build the launchd `Label` for a given service name.
pub fn launchd_label(service_name: &str) -> String {
    format!("{LABEL_PREFIX}.{service_name}")
}

/// Default plist path: `/Library/LaunchDaemons/com.veriguard.<service_name>.plist`.
pub fn default_plist_path(service_name: &str) -> PathBuf {
    PathBuf::from(DEFAULT_LAUNCHD_PLIST_DIR).join(format!("{LABEL_PREFIX}.{service_name}.plist"))
}

/// Render the launchd plist as a UTF-8 string. Pure — no I/O.
///
/// Fails only on invalid configuration (non-`[A-Za-z0-9_-]` identifier,
/// non-absolute path, non-UTF-8 path bytes) so a malicious caller can't
/// smuggle a `<key>` override past the renderer.
pub fn render_plist(config: &SystemdConfig) -> Result<String, InstallError> {
    validate_identifier(&config.service_name, "service_name")?;
    validate_identifier(&config.service_user, "service_user")?;
    validate_absolute(&config.binary_path, "binary_path")?;
    validate_absolute(&config.state_dir, "state_dir")?;

    let binary = config
        .binary_path
        .to_str()
        .ok_or(InstallError::NonUtf8Path("binary_path"))?;
    let state_dir = config
        .state_dir
        .to_str()
        .ok_or(InstallError::NonUtf8Path("state_dir"))?;
    let label = launchd_label(&config.service_name);

    let mut out = String::with_capacity(1500);
    writeln!(out, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>").unwrap();
    writeln!(
        out,
        "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \
         \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">"
    )
    .unwrap();
    writeln!(out, "<!-- Generated by veriguard-agent install (A.8.2) -->").unwrap();
    writeln!(
        out,
        "<!-- Re-running `veriguard-agent install` will overwrite this file. -->"
    )
    .unwrap();
    writeln!(out, "<plist version=\"1.0\">").unwrap();
    writeln!(out, "<dict>").unwrap();

    writeln!(out, "    <key>Label</key>").unwrap();
    writeln!(out, "    <string>{label}</string>").unwrap();

    writeln!(out, "    <key>ProgramArguments</key>").unwrap();
    writeln!(out, "    <array>").unwrap();
    writeln!(out, "        <string>{binary}</string>").unwrap();
    writeln!(out, "        <string>run</string>").unwrap();
    writeln!(out, "        <string>--state-dir</string>").unwrap();
    writeln!(out, "        <string>{state_dir}</string>").unwrap();
    writeln!(out, "    </array>").unwrap();

    writeln!(out, "    <key>UserName</key>").unwrap();
    writeln!(out, "    <string>{}</string>", config.service_user).unwrap();
    writeln!(out, "    <key>GroupName</key>").unwrap();
    writeln!(out, "    <string>{}</string>", config.service_user).unwrap();

    writeln!(out, "    <key>RunAtLoad</key>").unwrap();
    writeln!(out, "    <true/>").unwrap();
    writeln!(out, "    <key>KeepAlive</key>").unwrap();
    writeln!(out, "    <true/>").unwrap();

    writeln!(out, "    <key>WorkingDirectory</key>").unwrap();
    writeln!(out, "    <string>{state_dir}</string>").unwrap();
    writeln!(out, "    <key>StandardOutPath</key>").unwrap();
    writeln!(
        out,
        "    <string>/var/log/{}.out.log</string>",
        config.service_name
    )
    .unwrap();
    writeln!(out, "    <key>StandardErrorPath</key>").unwrap();
    writeln!(
        out,
        "    <string>/var/log/{}.err.log</string>",
        config.service_name
    )
    .unwrap();

    writeln!(out, "    <key>ProcessType</key>").unwrap();
    writeln!(out, "    <string>Background</string>").unwrap();

    writeln!(out, "</dict>").unwrap();
    writeln!(out, "</plist>").unwrap();
    Ok(out)
}

/// Install the launchd plist + (optionally) bootstrap it via `launchctl`.
///
/// In `dry_run` mode this prints the plist contents and returns without
/// touching disk or invoking `launchctl`. In real-run mode:
///
/// 1. Write the plist to [`default_plist_path`] with mode `0644`.
/// 2. If `enable_on_install`, run `launchctl bootstrap system <path>` so
///    the daemon starts immediately and re-loads at boot.
pub fn install_launchd(config: &SystemdConfig) -> Result<SystemdInstallReport, InstallError> {
    let unit_contents = render_plist(config)?;
    let unit_path = default_plist_path(&config.service_name);

    if config.dry_run {
        println!("--- {} (dry-run, not written) ---", unit_path.display());
        println!("{unit_contents}");
        return Ok(SystemdInstallReport {
            unit_path,
            unit_contents,
            wrote_unit_file: false,
            enabled: false,
        });
    }

    write_plist_file(&unit_path, &unit_contents)?;

    let enabled = if config.enable_on_install {
        launchctl_bootstrap(&unit_path)?;
        true
    } else {
        false
    };

    Ok(SystemdInstallReport {
        unit_path,
        unit_contents,
        wrote_unit_file: true,
        enabled,
    })
}

/// Bootout + remove the launchd plist, optionally purge `state_dir`. The
/// API and report shape mirror [`super::uninstall::uninstall_systemd`]
/// so callers don't need a platform-tagged config.
pub fn uninstall_launchd(
    config: &SystemdUninstallConfig,
) -> Result<SystemdUninstallReport, InstallError> {
    validate_identifier(&config.service_name, "service_name")?;
    let unit_path = default_plist_path(&config.service_name);
    let label = launchd_label(&config.service_name);

    if config.dry_run {
        println!("--- launchd uninstall dry-run plan ({}) ---", label);
        if config.disable_first {
            println!("would run: launchctl bootout system/{label}");
        }
        println!("would remove: {}", unit_path.display());
        if config.purge_state {
            println!(
                "would recursively delete state dir: {}",
                config.state_dir.display()
            );
        }
        return Ok(SystemdUninstallReport {
            unit_path,
            disabled: false,
            removed_unit: false,
            daemon_reloaded: false,
            purged_state: false,
        });
    }

    let disabled = if config.disable_first {
        match launchctl_bootout(&label) {
            Ok(()) => true,
            Err(InstallError::ToolNonZero { code, .. }) => {
                // launchctl returns non-zero ("no such process") if the
                // daemon wasn't loaded — treat that as already-disabled.
                log::warn!(
                    "launchctl bootout system/{label} returned {code:?} — treating as no-op"
                );
                false
            }
            Err(other) => return Err(other),
        }
    } else {
        false
    };

    let removed_unit = if unit_path.exists() {
        std::fs::remove_file(&unit_path).map_err(|e| InstallError::Io {
            op: "remove plist",
            path: unit_path.clone(),
            err: e.to_string(),
        })?;
        true
    } else {
        false
    };

    let purged_state = if config.purge_state {
        purge_state_dir(&config.state_dir)?
    } else {
        false
    };

    Ok(SystemdUninstallReport {
        unit_path,
        disabled,
        removed_unit,
        daemon_reloaded: false,
        purged_state,
    })
}

// ---- private I/O helpers ----------------------------------------------------

fn write_plist_file(path: &Path, contents: &str) -> Result<(), InstallError> {
    use std::fs;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| InstallError::Io {
            op: "create_dir_all plist parent",
            path: parent.to_path_buf(),
            err: e.to_string(),
        })?;
    }
    fs::write(path, contents).map_err(|e| InstallError::Io {
        op: "write plist file",
        path: path.to_path_buf(),
        err: e.to_string(),
    })?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(path)
            .map_err(|e| InstallError::Io {
                op: "stat plist file",
                path: path.to_path_buf(),
                err: e.to_string(),
            })?
            .permissions();
        perms.set_mode(0o644);
        fs::set_permissions(path, perms).map_err(|e| InstallError::Io {
            op: "chmod 0644 plist file",
            path: path.to_path_buf(),
            err: e.to_string(),
        })?;
    }
    Ok(())
}

fn launchctl_bootstrap(plist_path: &Path) -> Result<(), InstallError> {
    let path_str = plist_path
        .to_str()
        .ok_or(InstallError::NonUtf8Path("plist_path"))?;
    let status = Command::new("launchctl")
        .args(["bootstrap", "system", path_str])
        .status()
        .map_err(|e| InstallError::ToolSpawn {
            tool: "launchctl",
            err: e.to_string(),
        })?;
    if !status.success() {
        return Err(InstallError::ToolNonZero {
            tool: "launchctl",
            args: format!("bootstrap system {path_str}"),
            code: status.code(),
        });
    }
    Ok(())
}

fn launchctl_bootout(label: &str) -> Result<(), InstallError> {
    let target = format!("system/{label}");
    let status = Command::new("launchctl")
        .args(["bootout", &target])
        .status()
        .map_err(|e| InstallError::ToolSpawn {
            tool: "launchctl",
            err: e.to_string(),
        })?;
    if !status.success() {
        return Err(InstallError::ToolNonZero {
            tool: "launchctl",
            args: format!("bootout {target}"),
            code: status.code(),
        });
    }
    Ok(())
}

fn purge_state_dir(state_dir: &Path) -> Result<bool, InstallError> {
    if !state_dir.exists() {
        return Ok(false);
    }
    log::warn!(
        "launchd uninstall: purging state dir {} (destructive — keys wiped)",
        state_dir.display()
    );
    std::fs::remove_dir_all(state_dir).map_err(|e| InstallError::Io {
        op: "purge state_dir",
        path: state_dir.to_path_buf(),
        err: e.to_string(),
    })?;
    Ok(true)
}

// ---- tests ------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn cfg() -> SystemdConfig {
        SystemdConfig::default()
    }

    #[test]
    fn test_render_contains_required_keys() {
        let s = render_plist(&cfg()).unwrap();
        assert!(s.contains("<?xml version=\"1.0\""));
        assert!(s.contains("<plist version=\"1.0\">"));
        assert!(s.contains("<key>Label</key>"));
        assert!(s.contains("<string>com.veriguard.veriguard-agent</string>"));
        assert!(s.contains("<key>ProgramArguments</key>"));
        assert!(s.contains("<key>UserName</key>"));
        assert!(s.contains("<key>GroupName</key>"));
        assert!(s.contains("<key>RunAtLoad</key>"));
        assert!(s.contains("<key>KeepAlive</key>"));
        assert!(s.contains("<key>WorkingDirectory</key>"));
        assert!(s.contains("<key>StandardOutPath</key>"));
        assert!(s.contains("<key>StandardErrorPath</key>"));
        assert!(s.contains("<key>ProcessType</key>"));
        assert!(s.contains("<string>Background</string>"));
        assert!(s.ends_with("</plist>\n"));
    }

    #[test]
    fn test_render_uses_configured_paths_and_user() {
        let c = SystemdConfig {
            binary_path: PathBuf::from("/opt/veriguard/bin/agent"),
            state_dir: PathBuf::from("/var/lib/veriguard-fixture"),
            service_name: "fixture-agent".into(),
            service_user: "fixture-user".into(),
            enable_on_install: false,
            dry_run: true,
        };
        let s = render_plist(&c).unwrap();
        assert!(s.contains("com.veriguard.fixture-agent"));
        assert!(s.contains("/opt/veriguard/bin/agent"));
        assert!(s.contains("/var/lib/veriguard-fixture"));
        assert!(s.contains("<string>fixture-user</string>"));
        assert!(s.contains("/var/log/fixture-agent.out.log"));
        assert!(s.contains("/var/log/fixture-agent.err.log"));
    }

    #[test]
    fn test_render_rejects_bad_service_name() {
        let mut c = cfg();
        c.service_name = "bad name\nLABEL=hijack".into();
        let err = render_plist(&c).unwrap_err();
        match err {
            InstallError::IdentifierBadChar { field, .. } => {
                assert_eq!(field, "service_name");
            }
            other => panic!("expected IdentifierBadChar, got {other:?}"),
        }
    }

    #[test]
    fn test_render_rejects_relative_binary_path() {
        let mut c = cfg();
        c.binary_path = PathBuf::from("relative/path");
        let err = render_plist(&c).unwrap_err();
        match err {
            InstallError::PathNotAbsolute { field, .. } => {
                assert_eq!(field, "binary_path");
            }
            other => panic!("expected PathNotAbsolute, got {other:?}"),
        }
    }

    #[test]
    fn test_render_rejects_long_service_name() {
        let mut c = cfg();
        c.service_name = "a".repeat(65);
        let err = render_plist(&c).unwrap_err();
        match err {
            InstallError::IdentifierTooLong { field, len } => {
                assert_eq!(field, "service_name");
                assert_eq!(len, 65);
            }
            other => panic!("expected IdentifierTooLong, got {other:?}"),
        }
    }

    #[test]
    fn test_default_plist_path_format() {
        let p = default_plist_path("veriguard-agent");
        assert_eq!(
            p,
            PathBuf::from("/Library/LaunchDaemons/com.veriguard.veriguard-agent.plist")
        );
    }

    #[test]
    fn test_launchd_label_format() {
        assert_eq!(
            launchd_label("veriguard-agent"),
            "com.veriguard.veriguard-agent"
        );
        assert_eq!(launchd_label("custom-x"), "com.veriguard.custom-x");
    }

    #[test]
    fn test_install_dry_run_does_not_touch_disk() {
        let mut c = cfg();
        c.dry_run = true;
        let report = install_launchd(&c).unwrap();
        assert!(!report.wrote_unit_file);
        assert!(!report.enabled);
        assert!(report.unit_contents.contains("<plist"));
        assert!(!report.unit_path.exists()); // dry-run did not write
    }

    #[test]
    fn test_uninstall_dry_run_emits_plan() {
        let c = SystemdUninstallConfig {
            dry_run: true,
            ..SystemdUninstallConfig::default()
        };
        let report = uninstall_launchd(&c).unwrap();
        assert!(!report.disabled);
        assert!(!report.removed_unit);
        assert!(!report.purged_state);
    }
}
