//! Linux `systemd` service install (A.8.1).
//!
//! Renders a hardened `veriguard-agent.service` unit file and (optionally)
//! enables + starts it via `systemctl`.  The render path is pure-string
//! and fully unit-tested; the `systemctl` orchestration runs the real
//! commands only when not in dry-run mode.
//!
//! ## Hardening
//!
//! The generated unit applies a defensive baseline matching common
//! systemd service-hardening guides (RedHat / freedesktop.org):
//!
//! - `NoNewPrivileges=true`
//! - `PrivateTmp=true`
//! - `ProtectSystem=strict` (read-only `/usr`, `/boot`, `/etc`)
//! - `ProtectHome=read-only`
//! - `ProtectKernelTunables=true` / `ProtectKernelModules=true` / `ProtectControlGroups=true`
//! - `RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX` (no AF_NETLINK / raw sockets)
//! - `ReadWritePaths` set only to `state_dir` so the agent cannot stomp
//!   on host filesystem state outside its sandbox.
//!
//! Tightening (e.g. `CapabilityBoundingSet=`) is left to ops; the
//! defaults above keep the agent useful (HTTP poll + DNS) without giving
//! it root-equivalent reach.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

use super::error::InstallError;

/// Default path where the agent binary lives after a one-line curl install.
pub const DEFAULT_BINARY_PATH: &str = "/usr/local/bin/veriguard-agent";

/// Default state-dir for system-service installs (root-owned).
pub const DEFAULT_STATE_DIR: &str = "/var/lib/veriguard";

/// Default systemd unit name.
pub const DEFAULT_SERVICE_NAME: &str = "veriguard-agent";

/// Default service user / group created by a system install.
pub const DEFAULT_SERVICE_USER: &str = "veriguard";

/// Configuration for a systemd service install.
#[derive(Debug, Clone)]
pub struct SystemdConfig {
    /// Absolute path to the agent binary the unit will exec.
    pub binary_path: PathBuf,
    /// State directory passed to `veriguard-agent run --state-dir`.
    pub state_dir: PathBuf,
    /// Systemd unit name (no `.service` suffix — appended automatically).
    pub service_name: String,
    /// Service `User=` (also used for `Group=`).
    pub service_user: String,
    /// If true, run `systemctl daemon-reload && systemctl enable --now`.
    /// If false, only write the unit file.
    pub enable_on_install: bool,
    /// If true, print the rendered unit file and return without writing
    /// or invoking systemctl.
    pub dry_run: bool,
}

impl Default for SystemdConfig {
    fn default() -> Self {
        Self {
            binary_path: PathBuf::from(DEFAULT_BINARY_PATH),
            state_dir: PathBuf::from(DEFAULT_STATE_DIR),
            service_name: DEFAULT_SERVICE_NAME.to_string(),
            service_user: DEFAULT_SERVICE_USER.to_string(),
            enable_on_install: true,
            dry_run: false,
        }
    }
}

/// Outcome of a systemd install run — used by callers to print a useful
/// summary and by tests to assert behaviour without poking the real
/// systemd.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SystemdInstallReport {
    /// Where the unit file was written (or *would have been* in dry-run).
    pub unit_path: PathBuf,
    /// The exact bytes written / would have been written.
    pub unit_contents: String,
    /// Whether the unit file was actually written to disk.
    pub wrote_unit_file: bool,
    /// Whether `systemctl daemon-reload && enable --now` was invoked.
    pub enabled: bool,
}

/// Render the systemd unit file as a UTF-8 string.  Pure — no I/O.
///
/// Fails only on invalid configuration (e.g. shell-metacharacter in
/// `service_name` or `service_user`) so a malicious caller can't smuggle
/// a `[Service]` override past the renderer.
pub fn render_unit_file(config: &SystemdConfig) -> Result<String, InstallError> {
    validate_identifier(&config.service_name, "service_name")?;
    validate_identifier(&config.service_user, "service_user")?;
    validate_absolute(&config.binary_path, "binary_path")?;
    validate_absolute(&config.state_dir, "state_dir")?;

    let binary = config
        .binary_path
        .to_str()
        .ok_or(InstallError::NonUtf8Path("binary_path"))?;
    let state_dir = config
        .state_dir
        .to_str()
        .ok_or(InstallError::NonUtf8Path("state_dir"))?;

    let mut out = String::with_capacity(1024);
    // Header — track which fork built this unit so ops can grep for it.
    writeln!(out, "# Generated by veriguard-agent install (A.8.1)").unwrap();
    writeln!(
        out,
        "# Edit the [Service] block at your own risk; re-running `veriguard-agent install` will overwrite."
    )
    .unwrap();
    writeln!(out).unwrap();

    writeln!(out, "[Unit]").unwrap();
    writeln!(out, "Description=Veriguard Agent (C1)").unwrap();
    writeln!(
        out,
        "Documentation=https://github.com/wangjuelong/veriguard-agent"
    )
    .unwrap();
    writeln!(out, "After=network-online.target").unwrap();
    writeln!(out, "Wants=network-online.target").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "[Service]").unwrap();
    writeln!(out, "Type=simple").unwrap();
    writeln!(out, "User={}", config.service_user).unwrap();
    writeln!(out, "Group={}", config.service_user).unwrap();
    writeln!(out, "ExecStart={} run --state-dir {}", binary, state_dir).unwrap();
    writeln!(out, "Restart=on-failure").unwrap();
    writeln!(out, "RestartSec=10").unwrap();
    writeln!(out, "Environment=RUST_LOG=info").unwrap();
    writeln!(out).unwrap();

    // Hardening
    writeln!(
        out,
        "# Hardening — defaults applied by veriguard-agent install (A.8.1)."
    )
    .unwrap();
    writeln!(out, "NoNewPrivileges=true").unwrap();
    writeln!(out, "PrivateTmp=true").unwrap();
    writeln!(out, "ProtectSystem=strict").unwrap();
    writeln!(out, "ProtectHome=read-only").unwrap();
    writeln!(out, "ProtectKernelTunables=true").unwrap();
    writeln!(out, "ProtectKernelModules=true").unwrap();
    writeln!(out, "ProtectControlGroups=true").unwrap();
    writeln!(out, "RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX").unwrap();
    writeln!(out, "ReadWritePaths={}", state_dir).unwrap();
    writeln!(out).unwrap();

    writeln!(out, "[Install]").unwrap();
    writeln!(out, "WantedBy=multi-user.target").unwrap();

    Ok(out)
}

/// Default location for the systemd unit file (`/etc/systemd/system/<name>.service`).
pub fn default_unit_path(service_name: &str) -> PathBuf {
    PathBuf::from("/etc/systemd/system").join(format!("{service_name}.service"))
}

/// Install the systemd unit + (optionally) enable it via `systemctl`.
///
/// In `dry_run` mode this prints the unit contents and returns without
/// touching disk or invoking `systemctl`.
pub fn install_systemd(config: &SystemdConfig) -> Result<SystemdInstallReport, InstallError> {
    let unit_contents = render_unit_file(config)?;
    let unit_path = default_unit_path(&config.service_name);

    if config.dry_run {
        println!("--- {} (dry-run, not written) ---", unit_path.display());
        println!("{unit_contents}");
        return Ok(SystemdInstallReport {
            unit_path,
            unit_contents,
            wrote_unit_file: false,
            enabled: false,
        });
    }

    write_unit_file(&unit_path, &unit_contents)?;

    let enabled = if config.enable_on_install {
        systemctl_daemon_reload()?;
        systemctl_enable_now(&config.service_name)?;
        true
    } else {
        false
    };

    Ok(SystemdInstallReport {
        unit_path,
        unit_contents,
        wrote_unit_file: true,
        enabled,
    })
}

/// Write the unit file with mode `0644`.  Errors map to a typed
/// [`InstallError::Io`] so callers can show a meaningful permission
/// hint (typically "re-run with sudo").
fn write_unit_file(path: &Path, contents: &str) -> Result<(), InstallError> {
    use std::fs;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| InstallError::Io {
            op: "create_dir_all unit parent",
            path: parent.to_path_buf(),
            err: e.to_string(),
        })?;
    }
    fs::write(path, contents).map_err(|e| InstallError::Io {
        op: "write unit file",
        path: path.to_path_buf(),
        err: e.to_string(),
    })?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(path)
            .map_err(|e| InstallError::Io {
                op: "stat unit file",
                path: path.to_path_buf(),
                err: e.to_string(),
            })?
            .permissions();
        perms.set_mode(0o644);
        fs::set_permissions(path, perms).map_err(|e| InstallError::Io {
            op: "chmod 0644 unit file",
            path: path.to_path_buf(),
            err: e.to_string(),
        })?;
    }
    Ok(())
}

fn systemctl_daemon_reload() -> Result<(), InstallError> {
    let status = Command::new("systemctl")
        .arg("daemon-reload")
        .status()
        .map_err(|e| InstallError::SystemctlSpawn(e.to_string()))?;
    if !status.success() {
        return Err(InstallError::SystemctlNonZero {
            args: "daemon-reload".into(),
            code: status.code(),
        });
    }
    Ok(())
}

fn systemctl_enable_now(service_name: &str) -> Result<(), InstallError> {
    let status = Command::new("systemctl")
        .args(["enable", "--now", &format!("{service_name}.service")])
        .status()
        .map_err(|e| InstallError::SystemctlSpawn(e.to_string()))?;
    if !status.success() {
        return Err(InstallError::SystemctlNonZero {
            args: format!("enable --now {service_name}.service"),
            code: status.code(),
        });
    }
    Ok(())
}

/// Reject any character outside `[A-Za-z0-9_-]` so identifier values
/// cannot smuggle a `\n` or `=` into the unit file.
///
/// `pub(super)` so [`super::uninstall`] (A.8.4) can reuse the exact same
/// hardening check on its own `service_name` field.
pub(super) fn validate_identifier(value: &str, field: &'static str) -> Result<(), InstallError> {
    if value.is_empty() {
        return Err(InstallError::EmptyField(field));
    }
    if value.len() > 64 {
        return Err(InstallError::IdentifierTooLong {
            field,
            len: value.len(),
        });
    }
    for c in value.chars() {
        if !(c.is_ascii_alphanumeric() || c == '_' || c == '-') {
            return Err(InstallError::IdentifierBadChar { field, ch: c });
        }
    }
    Ok(())
}

fn validate_absolute(p: &Path, field: &'static str) -> Result<(), InstallError> {
    if !p.is_absolute() {
        return Err(InstallError::PathNotAbsolute {
            field,
            path: p.to_path_buf(),
        });
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cfg() -> SystemdConfig {
        SystemdConfig::default()
    }

    #[test]
    fn test_render_contains_required_sections() {
        let s = render_unit_file(&cfg()).unwrap();
        assert!(s.contains("[Unit]"));
        assert!(s.contains("[Service]"));
        assert!(s.contains("[Install]"));
        assert!(s.contains("Description=Veriguard Agent (C1)"));
        assert!(s.contains("WantedBy=multi-user.target"));
    }

    #[test]
    fn test_render_uses_default_paths() {
        let s = render_unit_file(&cfg()).unwrap();
        assert!(s.contains(
            "ExecStart=/usr/local/bin/veriguard-agent run --state-dir /var/lib/veriguard"
        ));
        assert!(s.contains("ReadWritePaths=/var/lib/veriguard"));
    }

    #[test]
    fn test_render_respects_custom_binary_path() {
        let mut c = cfg();
        c.binary_path = PathBuf::from("/opt/veriguard/bin/veriguard-agent");
        let s = render_unit_file(&c).unwrap();
        assert!(s.contains(
            "ExecStart=/opt/veriguard/bin/veriguard-agent run --state-dir /var/lib/veriguard"
        ));
    }

    #[test]
    fn test_render_respects_custom_state_dir() {
        let mut c = cfg();
        c.state_dir = PathBuf::from("/srv/veriguard");
        let s = render_unit_file(&c).unwrap();
        assert!(s.contains("--state-dir /srv/veriguard"));
        assert!(s.contains("ReadWritePaths=/srv/veriguard"));
    }

    #[test]
    fn test_render_respects_custom_user() {
        let mut c = cfg();
        c.service_user = "vg-svc".to_string();
        let s = render_unit_file(&c).unwrap();
        assert!(s.contains("User=vg-svc"));
        assert!(s.contains("Group=vg-svc"));
    }

    #[test]
    fn test_render_includes_hardening_directives() {
        let s = render_unit_file(&cfg()).unwrap();
        for directive in &[
            "NoNewPrivileges=true",
            "PrivateTmp=true",
            "ProtectSystem=strict",
            "ProtectHome=read-only",
            "ProtectKernelTunables=true",
            "ProtectKernelModules=true",
            "ProtectControlGroups=true",
            "RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX",
        ] {
            assert!(
                s.contains(directive),
                "missing hardening directive: {directive}\nfull:\n{s}"
            );
        }
    }

    #[test]
    fn test_render_rejects_empty_service_name() {
        let mut c = cfg();
        c.service_name = "".to_string();
        let err = render_unit_file(&c).unwrap_err();
        assert!(matches!(err, InstallError::EmptyField("service_name")));
    }

    #[test]
    fn test_render_rejects_newline_injection_in_user() {
        // A naive renderer would let `User=evil\n[Service]\nUser=root` swap the
        // running user.  validate_identifier must reject this.
        let mut c = cfg();
        c.service_user = "evil\n[Service]\nUser=root".to_string();
        let err = render_unit_file(&c).unwrap_err();
        assert!(matches!(
            err,
            InstallError::IdentifierBadChar {
                field: "service_user",
                ..
            }
        ));
    }

    #[test]
    fn test_render_rejects_equals_injection_in_service_name() {
        let mut c = cfg();
        c.service_name = "name=evil".to_string();
        let err = render_unit_file(&c).unwrap_err();
        assert!(matches!(
            err,
            InstallError::IdentifierBadChar {
                field: "service_name",
                ..
            }
        ));
    }

    #[test]
    fn test_render_rejects_relative_binary_path() {
        let mut c = cfg();
        c.binary_path = PathBuf::from("relative/path/veriguard-agent");
        let err = render_unit_file(&c).unwrap_err();
        assert!(matches!(
            err,
            InstallError::PathNotAbsolute {
                field: "binary_path",
                ..
            }
        ));
    }

    #[test]
    fn test_render_rejects_relative_state_dir() {
        let mut c = cfg();
        c.state_dir = PathBuf::from("relative/state");
        let err = render_unit_file(&c).unwrap_err();
        assert!(matches!(
            err,
            InstallError::PathNotAbsolute {
                field: "state_dir",
                ..
            }
        ));
    }

    #[test]
    fn test_render_rejects_oversized_identifier() {
        let mut c = cfg();
        c.service_name = "a".repeat(65);
        let err = render_unit_file(&c).unwrap_err();
        assert!(matches!(
            err,
            InstallError::IdentifierTooLong {
                field: "service_name",
                len: 65
            }
        ));
    }

    #[test]
    fn test_default_unit_path_format() {
        let p = default_unit_path("veriguard-agent");
        assert_eq!(
            p,
            PathBuf::from("/etc/systemd/system/veriguard-agent.service")
        );
    }

    #[test]
    fn test_install_dry_run_does_not_touch_disk() {
        let mut c = cfg();
        c.dry_run = true;
        let report = install_systemd(&c).unwrap();
        assert!(!report.wrote_unit_file, "dry-run must not write");
        assert!(!report.enabled, "dry-run must not enable");
        assert!(report.unit_contents.contains("[Service]"));
        assert_eq!(
            report.unit_path,
            PathBuf::from("/etc/systemd/system/veriguard-agent.service")
        );
    }

    #[test]
    fn test_install_dry_run_with_custom_state_dir() {
        let mut c = cfg();
        c.dry_run = true;
        c.state_dir = PathBuf::from("/opt/veriguard/state");
        let report = install_systemd(&c).unwrap();
        assert!(report
            .unit_contents
            .contains("--state-dir /opt/veriguard/state"));
        assert!(report
            .unit_contents
            .contains("ReadWritePaths=/opt/veriguard/state"));
    }
}
